import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Stack, useLocalSearchParams } from "expo-router";
import { useState } from "react";
import { ActivityIndicator, Alert, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { getProductsId, patchProductsIdStock, type ProductDetailDto } from "@stokmate/api-client";
import { formatKurus, formatStock, isNonNegativeInteger, productQueryKeys } from "@stokmate/domain";
import { useSession } from "../../src/session";

export default function ProductDetail(){const id=Number(useLocalSearchParams<{id:string}>().id);const {apiClient}=useSession();const qc=useQueryClient();const q=useQuery({queryKey:productQueryKeys.detail(id),queryFn:()=>getProductsId(id,undefined,apiClient.fetch).then(r=>r.data),enabled:Number.isInteger(id)});const [stock,setStock]=useState("");const mutation=useMutation({mutationFn:(value:number)=>patchProductsIdStock(id,{stock:value},undefined,apiClient.fetch).then(r=>r.data),onSuccess:data=>{qc.setQueryData(productQueryKeys.detail(id),(old:ProductDetailDto|undefined)=>({...old,...data}));void qc.invalidateQueries({queryKey:productQueryKeys.lists()});setStock("");Alert.alert("Kaydedildi","Stok sayımı güncellendi.")},onError:()=>Alert.alert("Hata","Stok güncellenemedi.")});if(q.isLoading)return <SafeAreaView style={s.center}><ActivityIndicator size="large"/></SafeAreaView>;if(q.isError||!q.data)return <SafeAreaView style={s.center}><Text style={s.error}>Ürün detayı yüklenemedi.</Text><Pressable onPress={()=>void q.refetch()}><Text style={s.link}>Yeniden dene</Text></Pressable></SafeAreaView>;const p=q.data;const save=()=>{const value=Number(stock);if(!isNonNegativeInteger(value)){Alert.alert("Geçersiz stok","Fiziksel sayım sıfır veya daha büyük bir tam sayı olmalıdır.");return}mutation.mutate(value)};const fields:[string,unknown][]=[["SKU",p.sku],["Barkod",p.barcode],["Kategori",p.categoryName],["Marka",p.brandName],["Tedarikçi",p.supplierName],["Satış fiyatı",formatKurus(p.price??0)],["Maliyet",formatKurus(p.costPrice??0)],["Birim",p.unit],["Durum",p.status],["Açıklama",p.description],["Öne çıkan",p.isFeatured?"Evet":"Hayır"],["Oluşturuldu",p.createdAt],["Güncellendi",p.updatedAt]];return <SafeAreaView style={s.safe}><Stack.Screen options={{title:p.name??"Ürün"}}/><ScrollView contentContainerStyle={s.content}><Text style={s.title}>{p.name}</Text><View style={s.card}><Text style={s.cardLabel}>Mevcut stok</Text><Text style={s.stock}>{formatStock(p.stock??0)}</Text><Text style={s.min}>Minimum stok: {formatStock(p.minStock??0)}</Text></View><Text style={s.section}>Fiziksel sayım</Text><TextInput value={stock} onChangeText={setStock} keyboardType="number-pad" placeholder="Nihai stok adedi" style={s.input} accessibilityLabel="Nihai fiziksel stok adedi"/><Pressable onPress={save} disabled={mutation.isPending} style={s.button}>{mutation.isPending?<ActivityIndicator color="#fff"/>:<Text style={s.buttonText}>Stoku güncelle</Text>}</Pressable><Text style={s.section}>Ürün bilgileri</Text>{fields.map(([label,value])=><View key={label} style={s.field}><Text style={s.fieldLabel}>{label}</Text><Text style={s.fieldValue}>{value==null||value===""?"—":String(value)}</Text></View>)}</ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#f8fafc"},content:{padding:20,gap:10},center:{flex:1,justifyContent:"center",alignItems:"center",gap:12},title:{fontSize:25,fontWeight:"700",color:"#0f172a"},card:{marginTop:8,borderRadius:12,backgroundColor:"#ccfbf1",padding:18},cardLabel:{color:"#115e59",fontWeight:"600"},stock:{color:"#134e4a",fontSize:32,fontWeight:"800",marginTop:4},min:{color:"#115e59",marginTop:4},section:{fontWeight:"700",fontSize:17,marginTop:16,color:"#0f172a"},input:{backgroundColor:"white",borderWidth:1,borderColor:"#cbd5e1",borderRadius:8,minHeight:48,paddingHorizontal:12},button:{alignItems:"center",backgroundColor:"#0f766e",borderRadius:8,minHeight:48,justifyContent:"center"},buttonText:{color:"white",fontWeight:"700"},field:{borderBottomColor:"#e2e8f0",borderBottomWidth:1,paddingVertical:10},fieldLabel:{color:"#64748b",fontSize:12},fieldValue:{color:"#0f172a",marginTop:3},error:{color:"#b91c1c"},link:{color:"#0f766e",fontWeight:"700"}});
