import { StyleSheet } from "react-native";

import { type MobileColors } from "../../src/preferences";

export function createProductListStyles(colors: MobileColors) {
  return StyleSheet.create({
    applyButton: {
      alignItems: "center",
      backgroundColor: colors.primary,
      borderRadius: 8,
      marginTop: 22,
      minHeight: 48,
      paddingHorizontal: 16,
    },
    applyButtonText: { color: colors.primaryForeground, fontWeight: "700" },
    center: {
      alignItems: "center",
      flex: 1,
      gap: 12,
      justifyContent: "center",
    },
    chip: {
      backgroundColor: colors.subtle,
      borderColor: colors.border,
      borderRadius: 20,
      borderWidth: 1,
      color: colors.text,
      paddingHorizontal: 10,
      paddingVertical: 5,
    },
    chips: {
      alignItems: "center",
      flexDirection: "row",
      gap: 10,
      marginVertical: 10,
    },
    container: { flex: 1, paddingHorizontal: 16 },
    error: { color: colors.danger, textAlign: "center" },
    filterButton: {
      borderColor: colors.primary,
      borderRadius: 9,
      borderWidth: 1,
      justifyContent: "center",
      minHeight: 46,
      paddingHorizontal: 12,
    },
    headerActions: { alignItems: "flex-end", flexDirection: "row", gap: 10 },
    footer: { alignItems: "center", padding: 20 },
    header: {
      alignItems: "center",
      flexDirection: "row",
      justifyContent: "space-between",
      paddingVertical: 16,
    },
    image: {
      backgroundColor: colors.subtle,
      borderRadius: 8,
      height: 54,
      width: 54,
    },
    label: {
      color: colors.text,
      fontWeight: "700",
      marginBottom: 7,
      marginTop: 16,
    },
    link: { color: colors.primary, fontWeight: "700" },
    loadButton: {
      borderColor: colors.primary,
      borderRadius: 8,
      borderWidth: 1,
      minHeight: 44,
      paddingHorizontal: 18,
      paddingVertical: 10,
    },
    lowStock: { color: colors.danger },
    muted: { color: colors.muted, marginTop: 3 },
    name: { color: colors.text, fontWeight: "700" },
    option: {
      borderColor: colors.border,
      borderRadius: 16,
      borderWidth: 1,
      minHeight: 40,
      paddingHorizontal: 10,
      paddingVertical: 7,
    },
    optionText: { color: colors.text },
    options: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
    price: { color: colors.primary, fontWeight: "600", marginTop: 3 },
    row: {
      alignItems: "center",
      borderBottomColor: colors.border,
      borderBottomWidth: 1,
      flexDirection: "row",
      gap: 12,
      minHeight: 76,
      paddingVertical: 10,
    },
    rowBody: { flex: 1 },
    safe: { backgroundColor: colors.background, flex: 1 },
    search: {
      backgroundColor: colors.card,
      borderColor: colors.border,
      borderRadius: 9,
      borderWidth: 1,
      color: colors.text,
      flex: 1,
      minHeight: 46,
      paddingHorizontal: 12,
    },
    searchLine: { flexDirection: "row", gap: 8 },
    scanButton: {
      alignItems: "center",
      borderColor: colors.primary,
      borderRadius: 9,
      borderWidth: 1,
      justifyContent: "center",
      minHeight: 46,
      paddingHorizontal: 10,
    },
    selectedOption: {
      backgroundColor: colors.subtle,
      borderColor: colors.primary,
    },
    shade: {
      backgroundColor: colors.overlay,
      flex: 1,
      justifyContent: "flex-end",
    },
    sheet: {
      backgroundColor: colors.card,
      borderTopColor: colors.border,
      borderTopLeftRadius: 18,
      borderTopRightRadius: 18,
      borderTopWidth: 1,
      maxHeight: "80%",
      paddingHorizontal: 20,
      paddingTop: 20,
    },
    sheetTitle: { color: colors.text, fontSize: 21, fontWeight: "700" },
    signOut: { justifyContent: "center", minHeight: 40 },
    stock: { color: colors.primary, fontWeight: "700" },
    title: { color: colors.text, fontSize: 27, fontWeight: "700" },
  });
}
